### ISSUE TITLE
Bare npm module import rewritten to relative path when a local file shares the module's name (regression in 1.9.0)

### ISSUE THREAD

**Issue by rmartins0** [justkey007/tsc-alias#261]
## Describe the bug

When a source file has the same base name as an npm package it imports, tsc-alias rewrites the bare module specifier into a relative path pointing at the file itself. This appears to be a regression introduced in **1.9.0** (works correctly in **1.8.17**).

## Reproduction

Given a file `src/redis.ts` that imports from the npm package of the same name:

```ts
// src/redis.ts
import { createClient } from 'redis';

const client = createClient();
```

With a typical setup (`tsc --noCheck && tsc-alias`), the compiled output on **1.9.0** becomes:

```js
const redis_1 = require("./redis"); // ❌ resolves to the file itself
```

instead of the correct:

```js
const redis_1 = require("redis");   // ✅ the npm package
```

Because the module ends up requiring itself, the named export is `undefined` at runtime:

```
TypeError: (0 , redis_1.createClient) is not a function
```

## Expected behavior

Bare module specifiers (npm packages) should never be rewritten to relative paths, regardless of whether a local file shares the same name. Only path aliases configured in `compilerOptions.paths` should be transformed.

## Version info

- tsc-alias **1.9.0** (regressed) — **1.8.17** works as expected
- **TypeScript 6.0.3**
- CommonJS output

Note: our `tsconfig.json` does **not** set the `baseUrl` property. `baseUrl` was deprecated in TypeScript 6.0 (and will stop functioning in TypeScript 7.0), so we intentionally rely only on `compilerOptions.paths` with relative path mappings. See the TypeScript 6.0 announcement: https://devblogs.microsoft.com/typescript/announcing-typescript-6-0/. This may be relevant if tsc-alias's resolution logic still assumes a `baseUrl` is present.

## Additional context

The clash occurs specifically when the imported package name equals the importing file's base name (e.g. a file named `redis.ts` importing the `redis` package).
